import day_07
import gleeunit
import gleeunit/should

pub fn main() {
  gleeunit.main()
}

const sample = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

// gleeunit test functions end in `_test`
pub fn part_1_test() {
  day_07.part_1(sample)
  |> should.equal(21)
}

pub fn part_2_test() {
  day_07.part_2(sample)
  |> should.equal(40)
}
